app-id: moe.ss16.hedgemodmanager
runtime: org.freedesktop.Platform
runtime-version: "24.08"
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.dotnet8
build-options:
  prepend-path: "/usr/lib/sdk/dotnet8/bin"
  append-ld-library-path: "/usr/lib/sdk/dotnet8/lib"
  prepend-pkg-config-path: "/usr/lib/sdk/dotnet8/lib/pkgconfig"

command: /app/bin/HedgeModManager.UI
finish-args:
  - --socket=x11
#  - --socket=wayland
#  - --socket=fallback-x11
  - --filesystem=host
  - --device=all
  - --share=ipc
  - --talk-name=org.freedesktop.DBus
  - --env=DOTNET_ROOT=/app/lib/dotnet
  - --system-talk-name=org.freedesktop.portal.Desktop

modules:
  - name: dotnet
    buildsystem: simple
    build-commands:
      - /usr/lib/sdk/dotnet8/bin/install.sh
  - name: app
    buildsystem: simple
    sources:
      - type: git
        branch: ui
        disable-shallow-clone: true
        url: https://github.com/hedge-dev/HedgeModManager.git
      - ./nuget-sources.json
    build-commands:
      - dotnet publish Source/HedgeModManager.UI/HedgeModManager.UI.csproj -c Release --no-self-contained --source ./nuget-sources
      - mkdir -p ${FLATPAK_DEST}/bin
      - cp -r Source/HedgeModManager.UI/bin/Release/net8.0/publish/* ${FLATPAK_DEST}/bin
